version: '3'

services:
        nginx:
                build: ./nginx/
                image: nginx
                restart: unless-stopped
                ports:
                - "443:443"
                depends_on:
                - wordpress
                networks:
                        - wordpress
                volumes:
                        - Wordpress:/var/www/html
        wordpress:
                build: ./wordpress/
                ports:
                - "9000"
                image: wordpress
                networks:
                        - wordpress
                depends_on:
                        - mariadb
                env_file:
                        - .env
                volumes:
                        - Wordpress:/var/www/html
        mariadb:
                build: ./mariadb/
                image: mariadb
                ports:
                        - "3306:3306"
                networks:
                        - wordpress
                volumes:
                        - Mariadb:/var/lib/mysql
                env_file:
                        - .env
                restart: always
volumes:
        Wordpress:
                driver_opts:
                        type: none
                        device: /Users/luna/data/Wordpress
                        o: bind
        Mariadb:
                driver_opts:
                        type: none
                        device: /Users/luna/data/Mariadb
                        o: bind
networks:
        wordpress:
                driver: bridge
